# Generated by Django 3.1.7 on 2021-03-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201106_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='wholes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpass', models.CharField(max_length=50)),
            ],
        ),
    ]
