# Generated by Django 3.1.7 on 2021-03-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_wholes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wholes',
        ),
    ]
