# Generated by Django 3.1.7 on 2021-04-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_wholesale_pass'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
