# Generated by Django 3.1.5 on 2021-01-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210101_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='baseprice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=10000),
            preserve_default=False,
        ),
    ]
