# Generated by Django 3.1.5 on 2021-01-04 19:19

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210104_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=builtins.callable),
        ),
    ]
